### ISSUE TITLE
spack error when running setup.sh

### ISSUE THREAD

**Issue by scottma** [aws-samples/hpc-workshop-wrf#5]
Encountered this issue when running setup.sh to install spack. Seems to be related to a recent change in spack.

NODE TYPE: HeadNode
I am the HeadNode node
Create Env
Cloning into '/shared/spack'...
==> Added 1 new compiler to /shared/spack/etc/spack/compilers.yaml
    gcc@7.3.1
==> Compilers are defined in the following files:
    /shared/spack/etc/spack/compilers.yaml
==> Error: <unknown file>:1: Additional properties are not allowed (404 was unexpected)
==> Error: <unknown file>:1: Additional properties are not allowed (404 was unexpected)

**Comment by usumfabricae** [comment]
Updated pcluster_install_spack.sh to cope with new releases of spack.
This workshop is mainly meant to be executed on graviton2 processors, it has not been fully tested on Intel or AMD cpus.
